### ISSUE TITLE
WebRTC API config endpoint does not include a plugin

### ISSUE THREAD

**Issue by DeAlexPesh** [strukturag/nextcloud-spreedme#73] opened 2017-02-08 11:23 UTC
.

**Comment by leonklingele** [comment] 2017-02-08 13:00
Hi @DeAlexPesh,

> Spreed.me: https://<domain>/spreed/
> Nextcloud: https://<domain>/cloud/

both of these URLs are actually using the same origin: an origin consists of a protocol, domain and port. Therefore, you can simply delete this file: `/var/www/nextcloud/apps/spreedme/extra/static/config/OwnCloudConfig.js`

This issue is a duplicate of #73. It was fixed with yesterday's 0.3.7 release.

**Comment by DeAlexPesh** [comment] 2017-02-08 13:09
.

**Comment by leonklingele** [comment] 2017-02-08 13:12
> but problem not is gone

Please upgrade to this app to version 0.3.7 which was released yesterday.

> This is screen from browser

This looks perfectly fine for me. Do video calls / chat work?

**Comment by DeAlexPesh** [comment] 2017-02-08 13:15
.

**Comment by DeAlexPesh** [comment] 2017-02-08 13:20
updated. now:
```
Spreed.ME Version 0.3.7

Ran test #1 (testOwncloudPhpConfigFile):
   Passed without an error

Ran test #2 (testOwncloudJavascriptConfigFile):
   Passed without an error

Ran test #3 (testSpreedWebRTCAPI):
   Passed without an error

Passed all tests. Everything seems to be set up correctly! :) 
```
but it's constantly updated with errors as on screen

**Comment by leonklingele** [comment] 2017-02-08 13:28
It looks like someone is closing the WebSocket connection.
Have you tried to proxy from nginx directly to Spreed WebRTC (leaving out the Apache-part)?
Any reason you turned off `proxy_buffering` in nginx?

**Comment by DeAlexPesh** [comment] 2017-02-08 15:53
now nginx:
```
  location ^~ /spreed {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade_spreed;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_http_version 1.1;
    proxy_connect_timeout 90;
    proxy_read_timeout 90;
    proxy_send_timeout 90;
    proxy_ignore_client_abort off;
    proxy_next_upstream error timeout invalid_header http_502 http_503 http_504;

    proxy_buffering on;
    proxy_buffer_size 4k;
    proxy_buffers 4 32k;
    proxy_busy_buffers_size 64k;
    proxy_temp_file_write_size 64k;	

    proxy_pass http://http_spreed;
    proxy_redirect off;
  }
```
I need copy "/var/www/nextcloud/apps/spreedme/extra" from nextcloud server to "/usr/share/spreed-webrtc-server/extra" spreed server? After remove "OwnCloudConfig.js" from spreed server Spreed.me say not found.

I can't leave apache part (
work sheme:
pfSense + haproxy (80 -> 443) -> https://nginx
https nginx (site) <-revers_proxy> apache2 (spreed.me) : 8081
https nginx (site) <-revers_proxy-> apache2 (nextcloud) : 80

**Comment by DeAlexPesh** [comment] 2017-02-08 16:25
.

**Comment by DeAlexPesh** [comment] 2017-02-09 05:25
.

**Comment by DeAlexPesh** [comment] 2017-02-10 11:47
.

**Comment by DeAlexPesh** [comment] 2017-02-10 11:55
Perhaps it is useful to someone: wsTest.html
```
<!DOCTYPE html>
<meta charset="utf-8" />
<head><title>WebSocket</title></head>

<body style="margin:0;">

<script language="javascript" type="text/javascript">

	var wsUri;
	var wsMsg;
	var output;

	function init() {
		wsUri = document.getElementById('ws').value;
		wsMsg = document.getElementById('mg').value;
		output = document.getElementById("output");
		output.innerHTML = ""
		testWebSocket();
	}

	function testWebSocket() {
		websocket = new WebSocket(wsUri);
		websocket.onopen = function(evt) { onOpen(evt) };
		websocket.onclose = function(evt) { onClose(evt) };
		websocket.onmessage = function(evt) { onMessage(evt) };
		websocket.onerror = function(evt) { onError(evt) };
	}

	function onOpen(evt) {
		writeToScreen("CONNECTED");
		doSend(wsMsg);
	}

	function onClose(evt) {
		writeToScreen("DISCONNECTED");
	}

	function onMessage(evt) {
		writeToScreen('<span style="color: #009;">RESPONSE: ' + evt.data + '</span>');
		websocket.close();
	}

	function onError(evt) {
		writeToScreen('<span style="color: #f00;">ERROR: ' + evt.data + '</span>');
	}

	function doSend(message) {
		writeToScreen('<span style="color: #090;">SENT: ' + message + '</span>');
		websocket.send(message);
	}

	function writeToScreen(message) {
		var pre = document.createElement("p");
		pre.style.wordWrap = "break-word";
		pre.innerHTML = message;
		output.appendChild(pre);
	}

</script>

<div style="padding: 10px; background: #222;">
	<input id="ws" type=text size="40" placeholder="wss://" value="wss://" />
	<input id="mg" type=text size="50" placeholder="Hello, World!" value="Hello, World!" />
	<input type=button onclick="init()" value="Test WebSocket" />
</div>

<div id="output" style="padding: 10px; background: #eee; border-bottom: 4px solid #222;"></div>

</body>
```

**Comment by leonklingele** [comment] 2017-02-10 12:43
Please try to make your setup simpler. It's so complex, there's no way I
can really help you except telling you to look at the logs.

As a first step, please check if Request -> nginx -> Spreed WebRTC works.
Then add Apache to your setup, ..

**Comment by DeAlexPesh** [comment] 2017-02-11 12:33
.

**Comment by DeAlexPesh** [comment] 2017-02-11 13:54
.

**Comment by leonklingele** [comment] 2017-02-13 09:43
Hi @DeAlexPesh and thanks for the details. The config looks and works just fine for me.

Have you tried the setup without Apache behind nginx, i.e. `request -> nginx -> Spreed WebRTC`?

**Comment by DeAlexPesh** [comment] 2017-02-13 13:34
.

**Comment by leonklingele** [comment] 2017-02-13 13:41
If you `listen = 127.0.0.1..`, then yes, it listens on lo.
To make it listen on other interfaces, either use `listen = 0.0.0.0..` (for all interfaces), or specify an IP explicitly.

**Comment by DeAlexPesh** [comment] 2017-02-13 13:46
.

**Comment by DeAlexPesh** [comment] 2017-02-13 13:53
.

**Comment by leonklingele** [comment] 2017-02-13 14:26
So you're running now without Apache? i.e. request -> nginx -> Spreed WebRTC? Which version of nginx do you use?
Configuration-wise I have no idea why it doesn't work for you. If it works with Apache but not with nginx, it must be related to nginx, no?

**Comment by DeAlexPesh** [comment] 2017-02-14 04:29
Yes, listen = 0.0.0.0.8080
request -> nginx -> Spreed WebRTC (ubuntu 16.04)
nginx version: nginx/1.9.10 (debian jessie)

Give me you contact please I'll show you how it works.

**Comment by leonklingele** [comment] 2017-02-14 09:25
Contact me via email if you prefer: [my-first-name-here]@struktur.de

**Comment by DeAlexPesh** [comment] 2017-02-18 12:22
worked, sorry I'm stupid. haproxy is wrong.

**Closed as completed** 2017-02-18 12:22 UTC

**Comment by qwertyuu** [comment] 2021-04-16 02:29
@DeAlexPesh What did you do? My friend uses haproxy and seems to have a similar problem
