### ISSUE TITLE
Room link is lacking scheme://hostname:port

### ISSUE THREAD

**Issue by longsleep** [strukturag/nextcloud-spreedme#53] opened 2016-10-13 14:26 UTC
The patched room link generator is not generating complete URLs. The scheme and host are missing. It generates links like `/apps/spreedme#abc`.

https://github.com/strukturag/nextcloud-spreedme/blob/develop/extra/static/owncloud.js#L123-L138

**Comment by leonklingele** [comment] 2016-10-13 14:50
It should get the base URL (incl. scheme, hostname and port) from 'ownCloud.getConfig().baseURL'.
Please make sure to disable/flush your browser cache and/or increase the app version which will have the same effect.

**Comment by longsleep** [comment] 2016-10-13 15:03
Well, this is a fresh install. Browser cache is disabled.

**Comment by leonklingele** [comment] 2016-10-14 08:30
Duplicate of #48 which already got fixed.

**Closed as completed** 2016-10-14 19:47 UTC
